/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c MmsAdaptor -a mmsadaptor ../../spec/org.nemomobile.MmsHandler.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef MMSADAPTOR_H_1390561457
#define MMSADAPTOR_H_1390561457

#include "mmspart.h"

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.nemomobile.MmsHandler
 */
class MmsAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.nemomobile.MmsHandler")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.nemomobile.MmsHandler\">\n"
"    <method name=\"messageNotification\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"imsi\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"from\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"subject\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"expiry\"/>\n"
"      <arg direction=\"in\" type=\"ay\" name=\"data\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"recId\"/>\n"
"    </method>\n"
"    <method name=\"messageReceiveStateChanged\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"recId\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"state\"/>\n"
"    </method>\n"
"    <method name=\"messageReceived\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"recId\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"mmsId\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"from\"/>\n"
"      <arg direction=\"in\" type=\"as\" name=\"to\"/>\n"
"      <arg direction=\"in\" type=\"as\" name=\"cc\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"subject\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"date\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"priority\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"cls\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"readReport\"/>\n"
"      <arg direction=\"in\" type=\"a(sss)\" name=\"parts\"/>\n"
"      <annotation value=\"MmsPartList\" name=\"org.qtproject.QtDBus.QtTypeName.In10\"/>\n"
"    </method>\n"
"    <method name=\"messageSendStateChanged\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"recId\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"state\"/>\n"
"    </method>\n"
"    <method name=\"deliveryReport\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"imsi\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"mmsId\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"recipient\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"status\"/>\n"
"    </method>\n"
"    <method name=\"readReport\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"imsi\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"mmsId\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"recipient\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"status\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    MmsAdaptor(QObject *parent);
    virtual ~MmsAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void deliveryReport(const QString &imsi, const QString &mmsId, const QString &recipient, int status);
    QString messageNotification(const QString &imsi, const QString &from, const QString &subject, uint expiry, const QByteArray &data);
    void messageReceiveStateChanged(const QString &recId, int state);
    void messageReceived(const QString &recId, const QString &mmsId, const QString &from, const QStringList &to, const QStringList &cc, const QString &subject, uint date, int priority, const QString &cls, bool readReport, MmsPartList parts);
    void messageSendStateChanged(const QString &recId, int state);
    void readReport(const QString &imsi, const QString &mmsId, const QString &recipient, int status);
Q_SIGNALS: // SIGNALS
};

#endif
