/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c MmsAdaptor -a mmsadaptor ../../spec/org.nemomobile.MmsHandler.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "mmsadaptor.h"
#include "mmshandler.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MmsAdaptor
 */

MmsAdaptor::MmsAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MmsAdaptor::~MmsAdaptor()
{
    // destructor
}

void MmsAdaptor::deliveryReport(const QString &imsi, const QString &mmsId, const QString &recipient, int status)
{
    // handle method call org.nemomobile.MmsHandler.deliveryReport
    QMetaObject::invokeMethod(parent(), "deliveryReport", Q_ARG(QString, imsi), Q_ARG(QString, mmsId), Q_ARG(QString, recipient), Q_ARG(int, status));
}

QString MmsAdaptor::messageNotification(const QString &imsi, const QString &from, const QString &subject, uint expiry, const QByteArray &data)
{
    // handle method call org.nemomobile.MmsHandler.messageNotification
    QString recId;
    QMetaObject::invokeMethod(parent(), "messageNotification", Q_RETURN_ARG(QString, recId), Q_ARG(QString, imsi), Q_ARG(QString, from), Q_ARG(QString, subject), Q_ARG(uint, expiry), Q_ARG(QByteArray, data));
    return recId;
}

void MmsAdaptor::messageReceiveStateChanged(const QString &recId, int state)
{
    // handle method call org.nemomobile.MmsHandler.messageReceiveStateChanged
    QMetaObject::invokeMethod(parent(), "messageReceiveStateChanged", Q_ARG(QString, recId), Q_ARG(int, state));
}

void MmsAdaptor::messageReceived(const QString &recId, const QString &mmsId, const QString &from, const QStringList &to, const QStringList &cc, const QString &subject, uint date, int priority, const QString &cls, bool readReport, MmsPartList parts)
{
    // handle method call org.nemomobile.MmsHandler.messageReceived
    static_cast<MmsHandler *>(parent())->messageReceived(recId, mmsId, from, to, cc, subject, date, priority, cls, readReport, parts);
}

void MmsAdaptor::messageSendStateChanged(const QString &recId, int state)
{
    // handle method call org.nemomobile.MmsHandler.messageSendStateChanged
    QMetaObject::invokeMethod(parent(), "messageSendStateChanged", Q_ARG(QString, recId), Q_ARG(int, state));
}

void MmsAdaptor::messageSent(const QString &recId, const QString &mmsId)
{
    // handle method call org.nemomobile.MmsHandler.messageSent
    QMetaObject::invokeMethod(parent(), "messageSent", Q_ARG(QString, recId), Q_ARG(QString, mmsId));
}

void MmsAdaptor::readReport(const QString &imsi, const QString &mmsId, const QString &recipient, int status)
{
    // handle method call org.nemomobile.MmsHandler.readReport
    QMetaObject::invokeMethod(parent(), "readReport", Q_ARG(QString, imsi), Q_ARG(QString, mmsId), Q_ARG(QString, recipient), Q_ARG(int, status));
}

