# -*- Mode: makefile-gmake -*-

all:
%:
	@$(MAKE) -C test_media_type $*
	@$(MAKE) -C test_mms_codec $*
	@$(MAKE) -C test_mms_log $*
	@$(MAKE) -C test_delivery_ind $*
	@$(MAKE) -C test_read_ind $*
	@$(MAKE) -C test_read_report $*
	@$(MAKE) -C test_resize $*
	@$(MAKE) -C test_retrieve $*
	@$(MAKE) -C test_retrieve_cancel $*
	@$(MAKE) -C test_retrieve_no_proxy $*
	@$(MAKE) -C test_send $*
