# -*- Mode: makefile-gmake -*-

all:
%:
	@$(MAKE) -C media_type $*
	@$(MAKE) -C mms_codec $*
	@$(MAKE) -C delivery_ind $*
	@$(MAKE) -C read_ind $*
	@$(MAKE) -C read_report $*
	@$(MAKE) -C resize $*
	@$(MAKE) -C retrieve $*
	@$(MAKE) -C retrieve_cancel $*
	@$(MAKE) -C retrieve_no_proxy $*
	@$(MAKE) -C send $*
